### ISSUE TITLE
Course id is invalid!

### ISSUE THREAD

**Issue by tareefdev** [skt-t1-byungi/femdown#2]
After the last fix, the package was working flawlessly. But today I got this error:

````
$ femdown https://frontendmasters.com/courses/css-in-depth-v2/

✖ Course id is invalid!
````
No matter which URL I use, it always returns the same error. Thanks for your great work.

**Comment by skt-t1-byungi** [comment]
Sorry, I stopped development. Frontendmasters suspends script user account. I realized that this project user was exposed to such risks. If you want to fix it, fork it yourself.
